name: Playwright Tests # Name of your workflow

on:
  push: # Trigger the workflow on every push
    branches: [ main, master ] # ...to the main branch (adjust if needed)
  pull_request:
    branches: [ main, master ]

jobs:
  test: # Define a job named "test"
    runs-on: ubuntu-latest # Use the latest Ubuntu image

    steps:
      - uses: actions/checkout@v4 # Checkout your repository's code
      - name: Set up Python # Set up the Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Use Python 3.13 (or your desired version)
      - name: Install dependencies # Install pytest-playwright and any other dependencies
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install pytest-playwright  # Corrected from pip install
          # Install any other project dependencies here
      - name: Install Playwright Browsers # Install the browsers Playwright needs
        run: |
          source .venv/bin/activate
          playwright install --with-deps
      - name: Run Playwright tests # Run your tests using pytest
        run: |
          source .venv/bin/activate
          pytest
      - uses: actions/upload-artifact@v4  # Optional: Upload test reports
        if: ${{ always() }}
        with:
          name: playwright-report
          path: test-results/  # Adjust this path if necessary
          retention-days: 1 # How long to keep the reports